version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: marketplace-postgres
    environment:
      POSTGRES_DB: marketplacedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:latest
    container_name: flyway-migrator
    depends_on:
      - postgres
    command: -connectRetries=15 -url=jdbc:postgresql://postgres:5432/marketplacedb -user=user -password=password migrate
    volumes:
      - ./migrations:/flyway/sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketplace-app
    depends_on:
      - flyway
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/marketplacedb?sslmode=disable
    ports:
      - "8080:8080"

volumes:
  postgres-data:
